### ISSUE TITLE
2016-02-15 release updates epic

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#692]
The [2016-02-15 release](https://getcarina.com/docs/reference/release-notes/#february-15-2016) contains a lot of goodness. We need to update all tutorials in light of this release.

Things to look at per tutorial:

* Should it use an overlay network?
 * If the tutorial uses multiple containers that need to communicate, they should probably use a network.
 * Like we use `mycluster` as the default cluster name, prefer `mynetwork` as the default network name (I'm open to suggestions on the network name).
 * `docker network create mynetwork` is the default command to use to create a network. If anything more complicated is required, it must be explained in the tutorial.
* Any use of `--link` must be removed.
* Is the tutorial still necessary?
* Does it need to be adjusted for any new features or bug fixes in Docker Engine [1.10.0](https://github.com/docker/docker/releases/tag/v1.10.0) or [1.10.1](https://github.com/docker/docker/releases/tag/v1.10.1)?
 * Update `docker-version` in the front matter.
* Does it need to be adjusted for any new features or bug fixes in Docker Swarm [1.1.0](https://github.com/docker/swarm/releases/tag/v1.1.0)?

Issues in the epic:

- [x] https://github.com/getcarina/getcarina.com/issues/705 @metral
* [x] https://github.com/getcarina/getcarina.com/issues/706 @mdarby  
* [x] https://github.com/getcarina/getcarina.com/issues/708 @jamiehannaford 
* [x] https://github.com/getcarina/getcarina.com/issues/709 @zack-shoylev 
* [x] https://github.com/getcarina/getcarina.com/issues/710 @everett-toews
* [x] https://github.com/getcarina/getcarina.com/issues/711 @smashwilson 
* [x] https://github.com/getcarina/getcarina.com/issues/712 @annegentle 
* [x] https://github.com/getcarina/getcarina.com/issues/713 @kmsholcomb 
* [x] https://github.com/getcarina/getcarina.com/issues/714 @carolynvs 
* [x] https://github.com/getcarina/getcarina.com/issues/715 @everett-toews
* [x] https://github.com/getcarina/getcarina.com/issues/716 @stephamon 
* [x] https://github.com/getcarina/getcarina.com/issues/717 @DonNateR 
* [x] https://github.com/getcarina/getcarina.com/issues/718 @everett-toews
* [x] https://github.com/getcarina/getcarina.com/issues/719 @rgbkrk 
* [x]  https://github.com/getcarina/getcarina.com/issues/720 @everett-toews

**Comment by carolynvs** [comment]
Why remove all usage of `--link`? Seems like it is still a useful and supported construct in 1.10, though isn't needed for the same scenarios as it was before. I was thinking we should rework networking tutorials to kill ambassador pattern and use links in slightly different scenarios.

**Comment by rgbkrk** [comment]
Were the uses of `--link` only related to networking, not volumes?

**Comment by everett-toews** [comment]
@carolynvs Links are now considered "[legacy](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)" and they [behave differently when used in the default docker0 bridge network compared to user-defined networks](https://docs.docker.com/engine/userguide/networking/dockernetworks/#links). I think this would be a real point of confusion for our users. I don't think we should be encouraging our users to work with legacy technology. However, I'm not aware of all the ways one might want to use a `--link`. Do you have a scenario that can only be solved with `--link` and that can't be solved with a `docker network`?

@rgbkrk Yes. If you wanted to "link" to a data volume container, you'd still use `--volumes-from`.

**Comment by carolynvs** [comment]
@everett-toews Okay I guess I'm confused by Docker's messaging on links. In their [public announcement](https://blog.docker.com/2016/02/docker-1-10/) they didn't call links "legacy" or discourage using them:

```
* Use links in networks: Links work in the default bridge network as they have always done,
  but you couldn’t use them in networks that you created yourself. We’ve now added support
  for this so you can define the relationships between your containers and alias a hostname
  to a different name inside a specific container (e.g. --link db:production_postgres).
* Network-wide container aliases: Links let you alias a hostname for a specific container,
  but you can now also make a container accessible by multiple hostnames across an entire network.
```

**Comment by everett-toews** [comment]
@carolynvs Ya. That's the confusing part to me. When using the default bridge, `--link` works like it used to. When using an overlay network, `--link` aliases a hostname. Same flag, two different behaviours in two different contexts.

I'd like to see use move towards ubiquitous use of overlay networks as they're more secure and allow your containers to run on any segment yet still access containers on other segments simply by name. In that case, using `--link` in the old context would be unnecessary now and only cause confusion.

Bizarrely, Docker doesn't even document in detail what `--link` does in the [run](https://docs.docker.com/engine/reference/commandline/run/) guide anymore. :disappointed: 

The caveat that I'm just getting up to speed on this stuff myself and could be out to lunch on the above. Let's keep working towards ubiquitous use of networks but reevaluate if they aren't working out like we think they do (like [what happened](https://github.com/docker/swarm/issues/1529) with `docker volume`).

**Comment by everett-toews** [comment]
The overlay networks tutorial is now published at [Use overlay networks in Carina](https://getcarina.com/docs/tutorials/overlay-networks/).

**Comment by everett-toews** [comment]
@lauracly All done.
