### ISSUE TITLE
Content Refresh Tracking - Mike Metral

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#705]
Here is the list of articles to review:

- [x] Container design philosophy
- [x] Container ecosystem: Kubernetes
- [x] Container ecosystem: Mesos versus OpenStack
- [x] Container ecosystem: OpenShift
- [x] Introduction to container technologies: Docker
- [x] Introduction to container technologies: market analysis
- [ ] Introduction to container technologies: container networking
- [x] Introduction to container technologies: container operating systems
- [x] Introduction to container technologies: orchestration and management of container clusters
- [x] Introduction to container technologies: registration and discovery of container services
- [x] Introduction to container technologies: scheduling and management of services and resources
- [ ] Docker best practices: container linking
- [x] Docker best practices: data and stateful applications
- [x] Docker best practices: Dockerfile
- [x] Docker best practices: image repository

**Comment by metral** [comment]
Hello,

None of the posts I wrote are affected by the changes in Carina as they're general to the container space and not tied nor based on Carina itself.

Consider all of these articles fine. :+1:

**Comment by lauracly** [comment]
Sounds good - thanks for the update. I will close this issue.

**Comment by everett-toews** [comment]
@metral @lauracly "Docker best practices: container linking" needs to be updated. Neither `--link` nor the ambassador pattern are recommended anymore. Both have been replaced by overlay networking. The current tutorials on `--link` nor the ambassador pattern are going to be removed and replaced by https://github.com/getcarina/getcarina.com/pull/726

**Comment by everett-toews** [comment]
"Introduction to container technologies: container networking" also needs to be updated to include the overlay (multi-host) networking native to Docker. This should also be the current recommendation for Docker-centric environments.

**Comment by lauracly** [comment]
Thanks for reopening @everett-toews.

**Comment by everett-toews** [comment]
@metral Can you give this a look this week or next?

**Comment by metral** [comment]
Apologies for the delay on this. I'll get to this very soon, promise!

**Comment by metral** [comment]
PR #741 has been pushed to resolve the remaining articles that needed update

**Comment by lauracly** [comment]
@metral can we close this issue? Looks like you updated everything in #741

**Comment by metral** [comment]
Yup. All good on my end

On Tuesday, March 8, 2016, lauracly <notifications@github.com> wrote:

> @metral <https://github.com/metral> can we close this issue? Looks like
> you updated everything in #741
> <https://github.com/getcarina/getcarina.com/pull/741>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getcarina/getcarina.com/issues/705#issuecomment-193954151>
> .
>


-- 
-Mike Metral
