### ISSUE TITLE
Content Refresh Tracking - Jamie Hannaford

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#708]
Here is the list of articles to review:

- [x] docker-swarm-carina.md Understanding how Carina uses Docker Swarm
- [x] docker-compose-with-carina.md Docker Compose with Carina
- [x] wordpress-apache-mysql.md Run WordPress, Apache, and MySQL in Docker
- [x] wordpress-nginx-links.md Run WordPress across linked front end and back end containers
- [x] autoscaling-carina.md Autoscaling resources in Carina

**Comment by jamiehannaford** [comment]
`docker-swarm-carina.md` *should* work, but I can't test a code block due to an [apparent bug](https://forums.docker.com/t/docker-ps-filter-does-not-work-against-ucp-endpoint/6578) in Docker.
