### ISSUE TITLE
Content Refresh Tracking - Zack Shoylev

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#709]
Here is the list of articles to review:

- [ ] Image-registries.md Image registries
- [ ] troubleshooting-windos-docker-vm-startup.md Troubleshooting the Docker Toolbox setup on Windows 7, 8.1, and 10
- [ ] mumble-on-carina.md Use Mumble on Carina
- [ ] quassel-on-carina.md Use Quassel on Carina

**Comment by zack-shoylev** [comment]
Thanks! I should be able to get to this later this week.

**Comment by zack-shoylev** [comment]
Note that some tutorial related images, such as the backup/restore ones, should also be updated.

**Comment by zack-shoylev** [comment]
https://github.com/getcarina/getcarina.com/pull/725

**Comment by zack-shoylev** [comment]
Images need to be updated with this when ready:

https://github.com/rackspace/rack/issues/389
