### ISSUE TITLE
Content Refresh Tracking - Everett Toews

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#710]
Here is the list of articles to review:

- [x] overview-of-carina.md	Overview of Carina
- [x] getting-started-on-carina.md	Getting started on Carina #722 
- [x] data-stores-mongodb.md	Use MongoDB on Carina
- [x] data-stores-mysql.md	Use MySQL on Carina
- [x] data-volume-containers.md	Use data volume containers
- [x] servicenet.md	Communicate between containers over the ServiceNet internal network
- [x] 070-troubleshooting.md	Troubleshooting common problems
- [x] registry-on-cloud-files.md	Store private Docker registry images on Cloud Files tutorial
