### ISSUE TITLE
Content Refresh Tracking - Carolyn Van Slyck

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#714]
Here is the list of articles to review:

- [x] aspnet-on-carina-with-visual-studio.md	Getting started with ASP.NET on Carina with Visual Studio
- [x] docker-networking-basics.md	Docker networking basics
- [x] publish-aspnet-to-carina.md	Publish an ASP.NET website to Carina from the command line
- [x] data-stores-mysql-prod.md	Connect a Carina container to a Rackspace cloud database
- [x] connect-docker-containers-with-links.md	Connect containers with Docker links
- [x] connect-docker-containers-ambassador-pattern.md	Connect containers by using the ambassador pattern
- [x] docker-version-manager.md	Manage Docker client versions with dvm
- [x] load-docker-environment-on-linux.md	Load a Docker environment from the command line on Linux
- [x] load-docker-environment-on-mac.md	Load a Docker environment from the command line on Mac OS X
- [x] load-docker-environment-on-windows.md	Load a Docker environment from the command line on Windows
- [x] preview-jekyll-with-docker-on-linux.md	Preview a Jekyll site with Docker on Linux
- [x] preview-jekyll-with-docker-on-mac.md	Preview a Jekyll site with Docker on Mac OS X
- [x] preview-jekyll-with-docker-on-windows.md	Preview a Jekyll site with Docker on Windows
- [x] run-container-using-custom-image.md	Error running a container using a custom image
- [x] troubleshooting-port-unavailable.md	Error publishing container to a specific port
- [x] troubleshooting-cannot-enable-tty-mode-on-windows.md	Error running interactive Docker shell on Windows

**Comment by carolynvs** [comment]
haha, that is a long list! :sweat_smile:

**Comment by lauracly** [comment]
Well you are prolific writer. I have faith in your. :)

**Comment by kenperkins** [comment]
Make sure you update the Jeykll-front matter for the new Docker version
