### ISSUE TITLE
Content Refresh Tracking - Nate Archer

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#717]
Here is the list of articles to review:

- [x] docker-101.md	Docker 101
- [x] run-docker-image.md	Find and download a Docker image
- [x] docker-install-linux.md	Install Docker on Linux
- [x] docker-install-mac.md	Install Docker on Mac OS X
- [x] docker-install-windows.md	Install Docker on Windows
- [x] set-up-docker-machine.md	Set up a virtual environment with a Docker host

**Comment by everett-toews** [comment]
@DonNateR Can you give this a look this week or next?

**Comment by DonNateR** [comment]
@everett-toews I'll take a look this afternoon or tomorrow morning.
