### ISSUE TITLE
March Newsletter (content due 3/22/16)

### ISSUE THREAD

**Issue by jnoller** [getcarina/getcarina.com#739]
First newsletter going out since launch in October to the user base. I've added a newsletter label to this repo, and other carina repos to flag anything that a potential for it.

- [ ] Content to be picked / surfaced by 3/20
- [ ] Newsletter draft to be done & reviewed by 3/28
- [ ] Newsletter to be sent by 3/29

**Comment by ktbartholomew** [comment]
@jnoller can we add some time in here to design a template for this newsletter? I don't think our plain-jane template or the one we used for inactive users will work very well for this kind of message. We'll want to put together something that's a little more forward with images and CTAs.

**Comment by jnoller** [comment]
Sure! Can we aim for end of month still?

**Comment by ktbartholomew** [comment]
I think we would need to move up the content pick deadline by a few days, then use the time between then and 3/28 to work out content and design simultaneously. But yes, 3/29 to send should still be doable.

**Comment by jnoller** [comment]
Sounds good, I'll edit when computered

**Comment by kimtryce** [comment]
Adjusting dates and objectives below.  Would like to send this out before the Carina Cantina at Openstack,  Please add any other items:

- [ ] Contentto be picked / surfaced by 4/13
- [ ] Newsletter draft to be done & reviewed by 4/18
- [ ] Newsletter to be sent by 4/20

**Comment by carolynvs** [comment]
We should have the doc/blog up for integrating with Carina by then so that should be fun to include. I updated your list with it.
