### ISSUE TITLE
CI/CD tutorial series epic

### ISSUE THREAD

**Issue by jamiehannaford** [getcarina/getcarina.com#816]
This issue tracks the CI/CD series, which will cover:
- [x] [How to set up push-based rolling deployment for your containers using XYZ](https://github.com/getcarina/getcarina.com/issues/817)
- [ ] [How to set up pull-based rolling deployment for your containers using Watchtower](https://github.com/getcarina/getcarina.com/issues/818)
- [ ] [Locally test and debug an ASP.NET website in a Docker container](https://github.com/getcarina/getcarina.com/issues/639)
- [ ] [Docker-based CI/CD for an ASP.NET website](https://github.com/getcarina/getcarina.com/issues/638)

Please feel free to edit this issue with any new ideas that can be featured.
